[tool.pytest.ini_options]
pythonpath = ["core", "app"]
minversion = "6.0"
python_files = "test_*.py"
addopts = [
    "-ra",
    "--strict-markers",
    "--cov=core",
    "--cov=app",
    "--cov-report=term-missing",
    "--debug=config"

]

testpaths = [
    "tests_pytest/unit",
    "tests_pytest/integration"
]

[tool.coverage.run]
branch = true
omit = [
    "tests/*",
    "*/__init__.py"
]

[tool.coverage.report]
show_missing = true
fail_under = 80


